/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export const recommended = {
  rules: {
    '@teapot-smashers/fetch/require-json-content-type': 'error',
    '@teapot-smashers/fetch/require-encoded-query-params': 'error',
    '@teapot-smashers/fetch/require-status-check': 'error',
    '@teapot-smashers/fetch/require-timeout': 'error',
    '@teapot-smashers/fetch/require-json-response-check': 'error',
    '@teapot-smashers/fetch/prefer-async-await': 'warn',
    '@teapot-smashers/fetch/require-error-handling': 'error',
    '@teapot-smashers/fetch/no-json-in-get-requests': 'error',
  },
};
