/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export const recommended = {
  rules: {
    '@teapot-smashers/fetch/require-json-content-type': 'error',
    '@teapot-smashers/fetch/require-encoded-query-params': 'error',
    '@teapot-smashers/fetch/require-status-check': 'error',
  },
};
