/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import requireJsonContentType from './rules/require-json-content-type';
import requireEncodedQueryParams from './rules/require-encoded-query-params';
import requireStatusCheck from './rules/require-status-check';

export const configs = {
  recommended,
};

export const rules = {
  'require-json-content-type': requireJsonContentType,
  'require-encoded-query-params': requireEncodedQueryParams,
  'require-status-check': requireStatusCheck,
};
